### ISSUE TITLE
Webpack: Uncaught TypeError: EC is not a constructor

### ISSUE THREAD

**Issue by Antanukas** [ConsenSys/eth-lightwallet#103]
When importing with Webpack `require("eth-lightwallet")` `Uncaught TypeError: EC is not a constructor` is thrown. 

Not sure if this is related to lightwallet it self. It seems that there is some dependency cycles in those crypo libs. Attached npm project with this issue
[test-webpack.zip](https://github.com/ConsenSys/eth-lightwallet/files/329385/test-webpack.zip)

`npm start` -> http://localhost:8080 -> open dev console

Currently workaround is to include full js file form dist `require("node_modules/eth-lightwallet/dist/lightwallet.js");`

**Comment by hugooconnor** [comment]
@Antanukas try removing '.' on line 25 of webpack.config.js

**Comment by Antanukas** [comment]
Heh it worked.
