### ISSUE TITLE
[Question] How can I use eth-lightwallet to verify a signature?

### ISSUE THREAD

**Issue by thiagodelgado111** [ConsenSys/eth-lightwallet#105]
I have the following message: '0xdeadbeefdeadbeefdeadbeef' and I'm using eth-lightwallet to sign it like this:
```
signedMsg = lightwallet.signing.signMsg(keystore, pwDerivedKey, '0xdeadbeefdeadbeefdeadbeef', '0xd5311ad626f09d0f9d1b1f7cdb84fdd600efbc1d');
```
It gives me this back: `0x348bdaeacdc93823b136f7d4f87a1c10be001de19a844c2d6751647a0c7fe5ee5451791e9696e08f815d851ad840c5a10a96cae9a5735d7c920bbfb39dfd30041c`. How can I verify a signed msg later? Using `recoverAddress`? is there an example of how to do that?

**Comment by danielnovy** [comment]
Take a look at the testing code here: https://github.com/ConsenSys/eth-lightwallet/blob/master/test/signing.js#L81

**Comment by thiagodelgado111** [comment]
oh, that will do the trick! :) thanks, @danielnovy!

**Comment by thiagodelgado111** [comment]
I'm trying to use it together with the web3.js `web3.eth.sign` method but I can't figure out what I'm doing wrong. It should give me back the address I used to sign the message, right?
