### ISSUE TITLE
`signTransaction` fails on Firefox build 48 with total length is larger than the data

### ISSUE THREAD

**Issue by dancirja3pg** [ConsenSys/eth-lightwallet#108]
When on Firefox build 48:

When trying to send a transaction and when trying to decode the sent transaction the following error is encountered:
`Error: invalid rlp: total length is larger than the data
_decode()
lightwallet.min.js:38
[417]</</exports.decode()
lightwallet.min.js:39
[382]</</exports.defineProperties()
lightwallet.min.js:37
[379]</</module.exports()
lightwallet.min.js:37
[4]</</signTx()
lightwallet.min.js:1
[3]</</KeyStore.prototype.signTransaction/</<()
lightwallet.min.js:1
[3]</</KeyStore.deriveKeyFromPassword/cb()
lightwallet.min.js:1
[418]</scrypt/</<()
lightwallet.min.js:39
[418]</scrypt/interruptedFor/<()
lightwallet.min.js:39
lightwallet.min.js:38:31274`

The error seems to happen when trying to do `input.slice` which returns the whole array instead of the sliced array. Digging deeper it looks like the `Buffer.subarray` method
works strangely on this version of Firefox (on earlier versions it seems to work fine). 
Does anybody encountered this issue?

(Tested with latest lightwallet 2.4.3)

**Comment by adrianciurdarean** [comment]
+1

**Comment by rdnorthup** [comment]
+1

**Comment by miladmostavi** [comment]
This should be fixed by https://github.com/ConsenSys/eth-lightwallet/pull/110

**Comment by dancirja3pg** [comment]
@miladmostavi Thanks for the fix.
