### ISSUE TITLE
keystore.createVault() returns callback twice

### ISSUE THREAD

**Issue by alanwunsche** [ConsenSys/eth-lightwallet#120]
When would the callback need to fire twice? 

```
lightwallet.keystore.createVault({
      password: password,
      seedPhrase: seedPhrase, // Optionally provide a 12-word seed phrase
      // salt: fixture.salt,     // Optionally provide a salt.
                             // A unique salt will be generated otherwise.
      // hdPathString: hdPath    // Optional custom HD Path String
      }, function (err, ks) {
        console.log(err);
        console.log(ks);
}
```

The two logs are returned twice.

The first time it works fine and returns ks

The second time, I return an err :

> TypeError: unexpected type [object String], use Uint8Array(…)

and then:

> Uncaught TypeError: unexpected type [object String], use Uint8ArraycheckArrayTypes @ lightwallet.js:60224
> nacl.secretbox.open @ lightwallet.js:60297
> KeyStore._decryptString @ lightwallet.js:364
> KeyStore.isDerivedKeyCorrect @ lightwallet.js:342
> KeyStore.generateNewAddress @ lightwallet.js:639
> (anonymous function) @ index.js:108
> (anonymous function) @ lightwallet.js:325
> cb @ lightwallet.js:764
> (anonymous function) @ lightwallet.js:56028
> (anonymous function) @ lightwallet.js:55993

The index.js:108  is in Meteor:
`global_keystore.generateNewAddress(password, numAddr);
`

**Comment by AugustoL** [comment]
Im having the same error here, any update on this?
