### ISSUE TITLE
Signature and nonce

### ISSUE THREAD

**Issue by Robien** [ConsenSys/eth-lightwallet#130]
Hello,

I noticed that when I use the signMsg function it always return the same value for the same input.
If I use the web3 console it is different each time.

I read that the digital signature algorithm need to use random nonce to generate the resulting signature.
It still works without it but it may be less safe.

What is the strategy used by eth-lightwallet? is it OK to not use a random value? are there a plan to implement it?

Thanks

**Comment by christianlundkvist** [comment]
Hi @Robien, we use the [RFC6979](https://tools.ietf.org/html/rfc6979) deterministic signature algorithm, which generates the nonce from the cipher text. The danger with nonce reuse is to use the same nonce for different messages, which doesn't happen here.

**Comment by christianlundkvist** [comment]
Hi @Robien, we use the [RFC6979](https://tools.ietf.org/html/rfc6979) deterministic signature algorithm, which generates the nonce from the cipher text. The danger with nonce reuse is to use the same nonce for different messages, which doesn't happen here.

**Comment by Robien** [comment]
Thank you for your reply.
I am not a specialist in security and I am glad to know you know your stuff :)

That perfectly answer my question.
