### ISSUE TITLE
Breaking cleanup upgrade: 3.0.0

### ISSUE THREAD

**Issue by christianlundkvist** [ConsenSys/eth-lightwallet#134]
Returning from a bit of an absence from Lightwallet I'm going to do a long overdue cleanup/refactoring release. Things that I intend to address are:

## Cruft/unused stuff

These things I don't think are used very much, makes the code bloated and complex and I intend on removing them:

* Encryption keys in the keystore
* Support for multiple HD paths (makes the function signatures and logic unnecessarily complex)
* Deprecated constructor (will use exclusively the new `createVault()`)
* Default salt, HD Path & duplicated key derivation functions

## Updated hex formats

When lightwallet was created it was unclear if addresses should have a `0x` prefix or not, so we opted to use without `0x`. Now it's clear that most applications use `0x` and this is even required in some places so we'll be switching to using `0x` exclusively.

## Feedback

If you have any other changes that you would like to see, please let us know here 😃

**Comment by cpetty-Novetta** [comment]
Bit plus for the hex format issue.

**Comment by jaycarey** [comment]
Does 'Encryption keys in the keystore' include removing the multiEncryptString / multiDecryptString functions? We use those a fair bit in our app.

**Comment by slothbag** [comment]
This is great, we use this library and think it is fantastic. Glad to see it is still being supported. 

We rely on serialize/deserialize the keystore to and from localStorage, and also the client side tx signing is super useful.

**Comment by christianlundkvist** [comment]
@jaycarey Good to know, thanks! The plan was to remove the explicit handling of encryption keys in the keystore itself. What I'll probably end up doing is to modify the encryption module to use a raw private key. That way you can still use it by exporting private keys from the keystore.

**Comment by tzapu** [comment]
just wanted to add that we rely on serializing/deserializing the keystore to and from a db, seems like a pretty big breaking change if that were to be removed

**Comment by christianlundkvist** [comment]
I have found the time to finish this up, will try to put up a pull request and merge in this today. Note that you'll need to update the following:

* Encryption keys are no longer indexed by public keys. If you wish to use encryption keys you will need to refer to them by the ethereum address of the corresponding private key 
* The `createVault` function is the only way to create new vaults right now, the old constructor is deprecated
* Addresses and raw transaction hex values are now prepended by `0x`, so you'll need to make sure your app can handle that
* There is only one `hdPath` in the keystore. If you need more than one you'll need to create more than one vault each with its own `hdPath`.
* You need to specifically choose an HD path, there is no default anymore.

@tzapu Serialization and deserialization is not removed.

**Comment by christianlundkvist** [comment]
This is now merged: #166
