### ISSUE TITLE
Bitcore-lib error on install and use -- more than one instance of bitcore-lib found..

### ISSUE THREAD

**Issue by SilentCicero** [ConsenSys/eth-lightwallet#137]
Uncaught Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (index.js:12)
    at Object.<anonymous> (index.js:15)
    at Object.131../lib/address (index.js:70)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.<anonymous> (mnemonic.js:3)
    at Object.122../errors (mnemonic.js:296)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.120../lib/mnemonic (index.js:1)

**Comment by oed** [comment]
Are you using the latest version? This should be solved in v2.5.4

**Comment by SilentCicero** [comment]
@oed just did. Works now thanks!

**Comment by ArjunRajJain** [comment]
this fix did not work

**Comment by amarantolaw** [comment]
Same issue on 2.5.6

**Comment by sc0Vu** [comment]
Hi @amarantolaw 

After read this https://github.com/bitpay/bitcore-lib/commit/73a8c83b5ef75889a0fdce220a30b02da3f1c5d5#diff-168726dbe96b3ce427e7fedce31bb0bc, they just add versionGuard again.

So I think we will get the same error if change the bitcore-lib version to 0.15.0.

Any other way to fix this?
Thanks!
