### ISSUE TITLE
bignumber.js dependency

### ISSUE THREAD

**Issue by lukehedger** [ConsenSys/eth-lightwallet#144]
Hey - just wondering the reason for the `bignumber` dependency referencing [a commit on a fork](https://github.com/ConsenSys/eth-lightwallet/blob/master/package.json#L59) rather than the main repo/latest version?

Thanks 🙃

**Comment by lk86** [comment]
This is now a serious issue, given that the fork has been deleted from github and the package is now impossible to install without modification.

**Comment by christianlundkvist** [comment]
@lk86 Thanks for the heads up! Mind doing a quick PR with the modification? What's the package you are using instead?

**Comment by lk86** [comment]
I don't know whether the official BigNumber.js package (https://github.com/MikeMcl/bignumber.js/) breaks anything, all of the other major ethereum js libraries are also using this debris fork (and also all broke today). It really should be a drop-in replacement but the version has changed from 2.0.7 to 4.0.2, so it will require some testing.

**Comment by christianlundkvist** [comment]
@lk86 Hmm, I'm looking through the code right now to see where I'm actually using this. It may be that I can remove this dependency. Of course I depend on other ethereum libs which as you say have this dependency as well.

**Comment by lk86** [comment]
The ethereum libs will be updated soon I'm sure, the contributors have been made aware of the issue and there are already some pull requests. If you can remove the dependency here that would be awesome.

**Comment by christianlundkvist** [comment]
I'll work on that, thanks again for getting it to my attention! 👍

**Comment by christianlundkvist** [comment]
@lk86 Ok I quickly tried removing the `bignumber.js` dependency and use the web3 PR fix temporarily  in `package.json`. This installs fine and all tests seem to pass. So it seems the bignumber dependency was legacy and can be removed.

**Comment by christianlundkvist** [comment]
@lk86 @lukehedger This is now fixed in https://github.com/ConsenSys/eth-lightwallet/pull/150. I will have to make another PR update once `web3` is updated.

**Comment by christianlundkvist** [comment]
Also updated on NPM: https://www.npmjs.com/package/eth-lightwallet

It works now, but I'm keeping this issue open and will close it once `web3` has been updated to deal with this.

**Comment by christianlundkvist** [comment]
Since `web3.js` is now fixed I've updated the dependency to version 0.19.1. It is done in this commit: https://github.com/ConsenSys/eth-lightwallet/commit/ada8c674aa7b5af821c4ca7fd137037ce0fbf618

Closing issue.
