### ISSUE TITLE
iOS Light Node

### ISSUE THREAD

**Issue by dominic-cei** [ConsenSys/eth-lightwallet#157]
Can anyone explain to me in more details about the use of these functions?

txutils.createContractTx(fromAddress, txObject)
txutils.functionTx(abi, functionName, args, txObject)

Actually, at first I thought these functions are use to deploy and interact with smart contracts on light node. I thought this light wallet is similar to Geth's light node wherein it can run light node and doesn't really need to run a full node on a server that we need to maintain.

**Comment by christianlundkvist** [comment]
@dominic-cei Lightwallet is not a light client, it is simply a key management solution. :)
