### ISSUE TITLE
Bitcore-lib double instance

### ISSUE THREAD

**Issue by Przemek-Win** [ConsenSys/eth-lightwallet#164]
Module eth-lightwallet and its' dependencies have some issue with bitcore-lib version guard. I noticed that some of them have version 0.15 and other 0.14.  Do you have any solution to this problem? Error that I receive is presented below.

````
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"]

Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (\GitHub\X\node_modules\eth-lightwallet\node_modules\bitcore-mnemonic\node_modules\bitcore-lib\index.js:12:11)
    at Object.<anonymous> (\GitHub\X\node_modules\eth-lightwallet\node_modules\bitcore-mnemonic\node_modules\bitcore-lib\index.js:15:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (\GitHub\X\node_modules\eth-lightwallet\node_modules\bitcore-mnemonic\lib\mnemonic.js:3:15)

Process finished with exit code 7`
```

**Comment by ArjunRajJain** [comment]
having the same error.

**Comment by Przemek-Win** [comment]
The solution provided there worked for me: https://github.com/bitpay/bitcore/issues/1454


> Well, this is far from a proper way to solve this issue, but you can get rid of this error by editing file
> 
> ~/.nvm/versions/node/v4.8.3/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js
> 
> line 7:
> bitcore.versionGuard = function(version) {
> Change it to:
> bitcore.versionGuard = function(version) { return;
> 
> I did this and so far no problems.

**Comment by eepstein** [comment]
This shouldn't be closed without a patch, IMO.  eth-lightwallet is directly including 0.14.0 of the library while indirectly including 0.15.0 of it via its dependence on bitcore-mnemonic.  Can't the direct dependence just be removed?

This thread shows a hack to work around the issue, but the issue remains.  Can it be fixed?

**Comment by Przemek-Win** [comment]
I was trying to remove the dependence on my own, but I believe it requires better knowledge of the module. I reopened the thread to wait for the patch.

**Comment by achadha235** [comment]
seems to me both eth-lighwallet and bitcore-mnemonic should be listing bitcore-lib ^0.15.0 as a peerDependency and not a dependency. Given the new behavior of npm install with peerDependencies, its up to clients using eth-lightwallet or bitcore-mnemonic to install bitcore-lib alongside. 

Am I totally off base here? I think there is a relevant PR here https://github.com/bitpay/bitcore-mnemonic/pull/26 that might help get all this going...

 https://docs.npmjs.com/all

**Comment by cneckar** [comment]
Monkey patching the dependency is a TERRIBLE solution, and doesn't work in a real deployment. Is this going to be fixed or do I need to migrate to another project?

**Comment by Exulansis** [comment]
Also facing this issue, so far I've been using the approach mentioned by @Przemek-Win, but it's clearly not sustainable...

**Comment by christianlundkvist** [comment]
Hey all, this will be fixed in the upcoming major cleanup: https://github.com/ConsenSys/eth-lightwallet/pull/166. This should be merged in sometime this week.

In the meantime you can use the `srirangan/eth-lightwallet` branch in which this issue is fixed.

**Comment by Exulansis** [comment]
Thank you!

**Comment by christianlundkvist** [comment]
Fixed now. :)

**Comment by bahi-2** [comment]
I was again getting this error and wrote my own workaround that doesn't force you to edit node module files, unlike the previous hack. When importing lightwallet do this:
**try {
var lightwallet = require('eth-lightwallet');
} catch (err) {
	delete global._bitcore
	var lightwallet = require('eth-lightwallet');
}**

It took me a while and I know it looks funny, but for some reason only after requiring it for the first time does deleting global._bitcore make a difference.
