### ISSUE TITLE
bitcore-lib double instance

### ISSUE THREAD

**Issue by eepstein** [ConsenSys/eth-lightwallet#167]
eth-lightwallet is directly including 0.14.0 of the library while indirectly including 0.15.0 of it via its dependence on bitcore-mnemonic. 

Can't the direct dependence just be removed?

this double dependency causes issues when being used in command-line tools.

**Comment by achadha235** [comment]
I think having peerDependencies set for a minimum version of bitcore-lib in bitcore-mnemonic could solve this ¯\_(ツ)_/¯

**Comment by christianlundkvist** [comment]
Please see this issue https://github.com/ConsenSys/eth-lightwallet/issues/164 for a fix.
