### ISSUE TITLE
404 at lightwallet.io?

### ISSUE THREAD

**Issue by bentoncbainbridge** [ConsenSys/eth-lightwallet#169]
https://lightwallet.io/ currently displays: 
(sorry if I'm reporting in the wrong place, Christian!)

<img width="1440" alt="screen shot 2017-11-09 at 6 26 04 pm" src="https://user-images.githubusercontent.com/11801545/32634809-7bdb7202-c57b-11e7-9653-d962b387eaab.png">
404  | The deployment could not be found.

**Comment by christianlundkvist** [comment]
@bentoncbainbridge as discussed over email you can use MEW to access a lightwallet mnemonic.
