### ISSUE TITLE
transaction stuck in pending

### ISSUE THREAD

**Issue by RamiroMoreira** [ConsenSys/eth-lightwallet#178]
Hello, i'm tring to make a value transaction as follows:

```
var countTransactions = web3.eth.getTransactionCount(fromAddress)
var txOptions = {
                    gasPrice: 90,
                    gasLimit: 2100002,
                    value: 1000,
                    to: "0xe13177062E7f56065f5d4eDaA22C80AE438A91aB",
                    chainId: 4,//Rinkeby
                    nonce: web3.utils.toHex(countTransactions)
}
var valueTx = txutils.valueTx(txOptions);
var signedValueTx = signing.signTx(thekeystore, pwDerivedKey,valueTx,fromAddress).toString("hex");
web3.eth.sendSignedTransaction("0x"+signedValueTx, function (err, res) {
}
```

but i get "Error: Transaction was not mined within 50 blocks, please make sure your transaction was properly send. Be aware that it might still be mined".
The transaction keep in pending forever, i don't know what i'm doing wrong. 
This is one of the transactions i send that get that error:
https://rinkeby.etherscan.io/tx/0x56dc927df472ab8423bbf878aa9d72853abc0341e987444c0608939614364615

**Comment by alexksso** [comment]
90 Wei is REALLY little for gas price - try again with 20 gWei 
(see here: https://www.rinkeby.io/#stats )

**Comment by RamiroMoreira** [comment]
thanks for answer, i just changed the gas price, same error:
 var txOptions = {
                    gasPrice: 200000000000,
                    gasLimit: 2100002,
                    value: amount,
                    to: toAddress,
                    //  data: undefined,
                    chainId: 4,//Rinkeby
                    nonce: web3.utils.toHex(nonceVal)
}

**Comment by alexksso** [comment]
says success :)

**Comment by alexksso** [comment]
where do you get the error again?

**Comment by alexksso** [comment]
btw I think you can close the issue as it's not an issue with the software here
