### ISSUE TITLE
Why was the bitcore-lib removed in 3.0.0 and added again in 3.0.1?

### ISSUE THREAD

**Issue by marcoskubis** [ConsenSys/eth-lightwallet#214]
In the release notes of the version 3.0.0, the `bitcore-lib` was removed (last line):
![image](https://user-images.githubusercontent.com/3844716/49554155-185f5b80-f8e2-11e8-9d91-162434e3e35e.png)

Why `bitcore-lib` was removed in 3.0.0 and added again in 3.0.1? [This commit](https://github.com/ConsenSys/eth-lightwallet/commit/e2c9f80ce9784284a3d6c603d3d2ea10bc09b3fa)
 It is conflicting with `bitcore-mnemonic`, that also requires `bitcore-lib`:

![image](https://user-images.githubusercontent.com/3844716/49554243-78ee9880-f8e2-11e8-8648-6ca3c6c6c340.png)
(electron app)

**Comment by dividezero** [comment]
From my investigations, the key cause is in the new 1.7.0 version of bitcore-mnemonic.
<img width="484" alt="screenshot 2018-12-04 at 3 44 39 pm" src="https://user-images.githubusercontent.com/1883831/49562905-7fb7f280-f958-11e8-806b-e05154bec3c8.png">

Specifically this commit 
https://github.com/bitpay/bitcore-mnemonic/commit/3ddf49e247ed1c396976eddf67f8c5c103aa3554

If we change lightwallet's dependency for it to retain 1.5.0 it shouldn't be an issue

**Comment by ameensol** [comment]
I just ran into this error as well.

**Comment by theomarshanti** [comment]
Same. Any fix?

**Comment by theomarshanti** [comment]
PR that solves it is here: https://github.com/ConsenSys/eth-lightwallet/pull/215

**Comment by sameepsi** [comment]
Any updates on this PR?

**Comment by sameepsi** [comment]
Looks like this project is no longer updated

**Comment by miladmostavi** [comment]
This was resolved in 4.0.0.
