### ISSUE TITLE
Lightwallet on meteor

### ISSUE THREAD

**Issue by Firescar96** [ConsenSys/eth-lightwallet#30]
Please fix light wallet so it can be installed in a meteor project and used server side. You'll see the problem if you install the module in a meteor project.

**Comment by inzhoop** [comment]
Hi  @Firescar96 did you find a solution to use Lightwallet on meteor?

**Comment by Firescar96** [comment]
@inzhoop I haven't tried using the package in a while so I'm not sure. The original problem was the use of a `XMLHttpRequest` call which I believe has been removed. It's also in the npm repositories now so you could try using it with the `meteorhacks:npm` package.

**Comment by hitchcott** [comment]
supported with PR #83

**Comment by Firescar96** [comment]
AMAZING

**Comment by retotrinkler** [comment]
wait does it work now? bec if i use it, it still freezes up my meteor instance

**Comment by vikasgrover2004** [comment]
@Firescar96 were u able to make lightwallet work in meteorjs application?

**Comment by Firescar96** [comment]
Sorry, I haven't gone back to try it, it's far back on my worklog, I will do it this weekend.

**Comment by hitchcott** [comment]
Just FYI, I've found it's simpler to just add ligthwallet.min.js to `/public` and manually link it in the `head`, rather than adding it to the meteor bundle. Keeps rebuild time down.

**Comment by Firescar96** [comment]
@hitchcott that won't help for running lightwallet serverside
@retotrinkler @vikasgrover2004 yes, hitchcott's PR solved my problem with both clientside and server side usage.
Run `import lightwallet from 'eth-lightwallet';` at the top level of your .js file.
