### ISSUE TITLE
Create keystore from seed using too few words throw out of range exception

### ISSUE THREAD

**Issue by danielnovy** [ConsenSys/eth-lightwallet#45]
Exact message thrown is: `RangeError: index out of range`. Message should be more user friendly, like: `Error: too few words provided` or something like this.

**Comment by christianlundkvist** [comment]
@danielnovy Hmm, I'm getting `KeyStore: Invalid mnemonic` as an error. Are you somehow using a valid mnemonic with fewer bits of randomness?

**Comment by danielnovy** [comment]
The message `Invalid mnemonic` is shown when you provide a word that is not on the list of words. If you provide words that are present on the list but provide fewer than 12 you will get the `RangeError`.

**Comment by christianlundkvist** [comment]
@danielnovy Ah you're right! I tried with 3 words from the list, and it gives me `Invalid mnemonic`. When I do 6 words it passes the test.

**Comment by christianlundkvist** [comment]
@danielnovy Pushed v1.0.1 which checks the number of words and if it's not 12 it throws the `Invalid mnemonic` mnemonic. Thanks for submitting! :)
