### ISSUE TITLE
Not working when installed with NPM3

### ISSUE THREAD

**Issue by simov** [ConsenSys/eth-lightwallet#46]
What error exactly do you get [here](https://github.com/ConsenSys/eth-lightwallet/blob/master/lib/keystore.js#L5-L7)?

This is bad practice and it should be resolved somehow. In NPM3 the node_modules directory structure is flat, so there is no such path when you install the module with NPM3.

Node >5.0.0 is bundled with NPM3 by default, so this might be a problem for a lot of people.

**Comment by christianlundkvist** [comment]
Hi @simov, this is the error I'm getting:

```
"Uncaught Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency."
```

This happens when I do `require('bitcore-lib')` in the source and add `bitcore-lib` in package.json. Did you try doing this with NPM3?

**Comment by simov** [comment]
It seems that they are checking for version mismatch, not for multiple instances in general, which is good.

As long as you have your dependency set in the exact same way as it is set in [bitcore-mnemonic](https://github.com/bitpay/bitcore-mnemonic/blob/master/package.json) 

```
"bitcore-lib": "^0.13.7"
```

it should work. 

When using NPM2 it should download the latest version in both places, which currently is [0.13.11](https://www.npmjs.com/package/bitcore-lib). 

When NPM3 flattens out the directory structure it will create just one instance of the module under the root of node_modules, if both versions matches.

You need to `npm update` in your project's dir after you update your package.json, or just remove node_modules and make a clean install just to be sure.

**Comment by christianlundkvist** [comment]
Ah, ok, that makes sense. I'll try that!

**Comment by simov** [comment]
No idea how is this going to work in the browser btw, but I'm assuming browserify relies on what npm offers.

**Comment by christianlundkvist** [comment]
@simov OK, I tried your suggestion and it works now! Thanks so much! I'm pushing out a large upgrade today, and I'll make sure to include this fix.

**Comment by christianlundkvist** [comment]
@simov I pushed a change that should fix it. I haven't updated to NPM 3 yet, would be thankful if you could test it on your end. Cheers!

**Comment by simov** [comment]
Seems to be working, thanks for the quick response :+1: 

As for node and npm versions you can use [nvm](https://github.com/creationix/nvm) for that.
