### ISSUE TITLE
harden bignumber.js dep to git commit

### ISSUE THREAD

**Issue by kumavis** [ConsenSys/eth-lightwallet#47]
bignumber.js is currently pointing at a git branch. this is a little bit dangerous, breaking changes could be introduced.

**Comment by christianlundkvist** [comment]
Yep, good idea, will do.

**Comment by christianlundkvist** [comment]
Fixed in https://github.com/ConsenSys/eth-lightwallet/commit/97985df84abb90ef10dd1ef488bcb995dcd846a5.
