### ISSUE TITLE
Feature Request: sign message

### ISSUE THREAD

**Issue by kumavis** [ConsenSys/eth-lightwallet#48]
While not used by web3, there is an RPC method for signing arbitrary messages. https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sign

lightwallet should provide a method for handling this

**Comment by tymat** [comment]
:+1:

**Comment by christianlundkvist** [comment]
Great suggestion! Will implement!

**Comment by tymat** [comment]
Any updates on this?

**Comment by christianlundkvist** [comment]
I haven't had time to implement, but it's on the roadmap. Need to look at the link that @kumavis sent to make sure what gets implemented is compatible with the RPC spec.

**Comment by kumavis** [comment]
yey! :smile_cat:

**Comment by tymat** [comment]
Thanks!
