### ISSUE TITLE
Feature Request - check password for correctness

### ISSUE THREAD

**Issue by kumavis** [ConsenSys/eth-lightwallet#52]
since we know the correct result addresses, we can check the entered password for correctness
there should be a method for this

**Comment by christianlundkvist** [comment]
We're also saving the hash of the password-derived key, so it should be easy to check. Did you mean you wanted a function `isCorrectPassword(pw)` or something like that?

**Comment by kumavis** [comment]
> Did you mean you wanted a function isCorrectPassword(pw) or something like that?
yes. a non-explodey way of attempting a password.

**Comment by dipenjoshi** [comment]
agree with kumavis. a function to check validating keystore passwords would be nice. Can be used to authenticate users

**Comment by christianlundkvist** [comment]
Added function `keystore.isDerivedKeyCorrect()` in https://github.com/ConsenSys/eth-lightwallet/releases/tag/v2.2.0
