### ISSUE TITLE
deserialize function is not part of the API ?

### ISSUE THREAD

**Issue by sponnet** [ConsenSys/eth-lightwallet#53]
Why is this function not part of the API ? I guess I should be able to deserialize a wallet that I have serialized before ?
Is this something that is missing in the code - or am I doing something wrong?

Thanks.
Stefaan

**Comment by ajunge** [comment]
It is: https://github.com/ConsenSys/eth-lightwallet#keystoredeserializeserialized_keystore

Saludos
Andres

**Comment by christianlundkvist** [comment]
Hi Stefaan,

The deserialized function needs to be called from the main `keystore` module since its a generic function. It cannot be called from a specific instance of `keystore`. Perhaps this is the root of your question?
