### ISSUE TITLE
Question: How to provide password to signTransaction()

### ISSUE THREAD

**Issue by alanwunsche** [ConsenSys/eth-lightwallet#57]
My implementation of sendEth() in the example webwallet.html always prompts for password with a dialog box even though the global_keystore is set. Is it possible to request password from a web form and pass it, and prevent the browser dialog box in KeyStore.prototype.signTransaction and passwordProvider?

**Comment by christianlundkvist** [comment]
Hi Alan, yes, you can override the function `passwordProvider` to read from something like a local cache. That would suppress the dialog box.
