### ISSUE TITLE
TypeError: Uint8Array.from is not a function - Safari 9.0.3 OSX 10.11.3

### ISSUE THREAD

**Issue by niksmac** [ConsenSys/eth-lightwallet#59]
> TypeError: Uint8Array.from is not a function. (In 'Uint8Array.from(e)', 'Uint8Array.from' is undefined)

on lightwallet.min.js:1:10611

**This error is in Safari Version 9.0.3 (11601.4.4) OSX 10.11.3**

**Comment by christianlundkvist** [comment]
Thanks! Apparently Safari has a slightly different implementation of Uint8Array than other browsers. I'll try using "new" there and see if it helps.

**Comment by christianlundkvist** [comment]
Fixed in https://github.com/ConsenSys/eth-lightwallet/commit/97985df84abb90ef10dd1ef488bcb995dcd846a5.
