### ISSUE TITLE
Any chance of getting the non minified version included in the dist output

### ISSUE THREAD

**Issue by slothbag** [ConsenSys/eth-lightwallet#63]

**Comment by christianlundkvist** [comment]
This is now included in https://github.com/ConsenSys/eth-lightwallet/commit/f58a062fbe8da1ff87853fa741b60bf6340d113b.

**Comment by slothbag** [comment]
Thanks, I just had a go at including the non-minified version in my project which has its own minify toolchain.. it failed trying to minify lightwallet.js  so then I tried to upload it to http://jscompress.com and it also fails to compress the file.

So not sure why that is.. when I include the non-minified version in my browser it appears to work ok.

This is a (very) low priority issue.
