### ISSUE TITLE
sendTransaction is now broken on Homestead geth 

### ISSUE THREAD

**Issue by tymat** [ConsenSys/eth-lightwallet#76]
getting an `Invalid sender` error in sendTransaction.  Upgraded geth to the latest Homestead release.

**Comment by christianlundkvist** [comment]
Hmm, I wonder if this is related to latest version of homestead  doing stricter signature checks? Have you checked that you're on the latest version of ethereumjs-tx (1.1.1)?

**Comment by tymat** [comment]
It's on  ethereumjs-tx 0.6.11

**Comment by christianlundkvist** [comment]
Let me know if it works when updating to latest version.
