### ISSUE TITLE
Minify process fails with this library

### ISSUE THREAD

**Issue by slothbag** [ConsenSys/eth-lightwallet#77]
I noticed a week ago that including lightwallet.js would cause my minify build process to fail, but if I used the lightwallet.min.js it would build fine.  

I just updated to lightwallet to 2.2.5 and now it seems both normal and min versions cause my minify to fail.

It also fails to compress here: http://jscompress.com/

**Comment by christianlundkvist** [comment]
Hi @slothbag! We were able to run the minification with the changes in 2.2.5. Earlier the minification succeeded but would lead to strange behavior like infinite loops.

**Comment by slothbag** [comment]
I'm using http://ajaxmin.codeplex.com/ to minify about a dozen different libraries at build time, it seems it doesn't like this latest eth-lightwallet :(

According to their docs they don't support eval statements which I found in the lightwallet src.. not sure if thats the cause though.

Guess i'll have to look to move to a more "up-to-date" minifier tool.

**Comment by christianlundkvist** [comment]
Hi @slothbag, do you know where the `eval` stuff is in the code? Would be good to not have that around...

**Comment by slothbag** [comment]
I just did a search on the minified code.. so it could be any one of the many dependencies..

I'll have to do some more tests.

**Comment by slothbag** [comment]
Looks like this library is included in the final output
https://github.com/tlsnotary/pagesigner/blob/master/content/verifychain/asn1.js2

which contains some evals like here:
https://github.com/tlsnotary/pagesigner/blob/master/content/verifychain/asn1.js2#L5362

I'm not 100% sure if this is the cause of the minify process though.

**Comment by slothbag** [comment]
Excluding this library from custom minification process.  Its not a big issue.
