### ISSUE TITLE
unable to pass input data with a value tx

### ISSUE THREAD

**Issue by southbite** [ConsenSys/eth-lightwallet#81]
in the valueTx method, we are unable to pass in some input data:
https://github.com/ConsenSys/eth-lightwallet/blob/master/lib/txutils.js#L92

is this by design?

the following code is commented to show the additional line:

```javascript
function valueTx (txObject) {
  // txObject contains gasPrice, gasLimit, value, nonce

  var txObjectCopy = {};
  txObjectCopy.to = add0x(txObject.to);
  txObjectCopy.gasPrice = add0x(txObject.gasPrice);
  txObjectCopy.gasLimit = add0x(txObject.gasLimit);
  txObjectCopy.nonce = add0x(txObject.nonce);
  txObjectCopy.value = add0x(txObject.value);
  //NB NB NB added this here - should we do a pull request?
  txObjectCopy.data = txObject.data;

  var tx = new Transaction(txObjectCopy);

  return tx.serialize().toString('hex');
}
```

BTW - thanks so much for your efforts, really great little library!

**Comment by christianlundkvist** [comment]
Hi southbite, yes this is by design. valueTx is only for sending value. Do you have a usecase where you want to include data but not call a function of a contract?

**Comment by southbite** [comment]
thanks for your response Christian! the line of thinking was to pass some input data (like an IPFS hash for instance) with a zero value transaction - haven't done the costing yet, but if a DAPP turns out to be as cheap or cheaper then I suppose your thinking is "why bother?" - but if a DAPP is more expensive - or fluctuates more, then it still makes sense even in Ethereum to use zero value transactions for small bits of data. I also found TX's to be more reliable than calls to DAPPs (had DAPP call TX's just disappearing into the ether) - but this may be how I am using the API (early days)... Also - it may be nice to be able to pass a reference in with a TX, as you never know what may be checking the TX on the back-end...? Or am I missing something completely and you guys have provision for passing in an input value somewhere else?

**Comment by christianlundkvist** [comment]
Well, sending data along with value transactions and then searching the blockchain transaction set for that data is a bit of an anti-pattern in Ethereum. Decentralized applications are designed to primarily get information from the state-tree and not from past transactions, so normally this means its better to write a smart contract and store the data there. This allows for more efficient blockchain pruning, light-clients and other good stuff.
