### ISSUE TITLE
AssertionError invalid chainCode size in Microsoft Edge

### ISSUE THREAD

**Issue by promethe42** [ConsenSys/eth-lightwallet#84]
Hi,

I'm using eth-lightwallet to generate accounts in the browser. Everything works great in Firefox (45.0.2, Windows and Ubuntu) and Chrome (49.0.2623, Windows, Ubuntu and Android).

But in Microsoft Edge (25.10586.0.0) I get the following error and I traced it back to bitcore-lib (https://github.com/bitpay/bitcore-lib):

```
AssertionError: chainCode has not the expected size: found 64, expected 32
```

The assertion error is raised here:

https://github.com/bitpay/bitcore-lib/blob/b3b18d532ff86855a142688413f60364aec4048a/lib/hdprivatekey.js#L464

My first guess is this buffer is initialized/filled twice in Microsoft Edge for some reason.
Could it be eth-lightwallet misusing bitcore-lib?
Can anyone confirm this part of bitcore-lib works in an app in Microsoft Edge?

How can we fix this?

Thank you !

**Comment by christianlundkvist** [comment]
Should be fixed in https://github.com/ConsenSys/eth-lightwallet/pull/110.

**Comment by promethe42** [comment]
Tested & Working.

:100:
