### ISSUE TITLE
Can't deploy a contract

### ISSUE THREAD

**Issue by pjworrall** [ConsenSys/eth-lightwallet#86]
TIA
Am I supposed to be able to deploy a contract over web3 using eth-lightwallet?
I have a valid Solidity contract. The js code is taken from Web3 deploy in Solidity Browser. When run from geth with loadScript() is works.

If I use the same code in the context of a js with the eth-wallet API I get  an:
Error: Gas price too low for acceptance .

Code is as follows:

`var ethClient = "http://localhost:xxxx";
var web3 = new Web3();
var global_keystore;

// setting up a web3 provider but using a keystore to get access to account information
function setWeb3Provider(keystore) {
    var web3Provider = new HookedWeb3Provider({
        host: ethClient,
        transaction_signer: keystore
    });
    web3.setProvider(web3Provider);
}

function setSeed() {
    var password = prompt('Enter Password to encrypt your seed', 'Password');
    var providedSeed = document.getElementById('seed').value;
    lightwallet.keystore.deriveKeyFromPassword(password, function (err, pwDerivedKey) {
        global_keystore = new lightwallet.keystore(
            providedSeed,
            pwDerivedKey);
        global_keystore.generateNewAddress(pwDerivedKey, 2);
        setWeb3Provider(global_keystore);
    });
}

function create() {
    var addresses = global_keystore.getAddresses();
    var c = web3.eth.contract(myAbi);
    var cInstance = c.new(
        {
            from: addresses[0],
            data: '........',
            gas: 3000000000000
        }, function(e, contract){
            console.log(e, contract);
            if (typeof contract != 'undefined') {
                console.log('Contract mined! address: ' + contract.address + ' transactionHash: ' + contract.transactionHash);
                console.log(contract.address);
            }
        });
}
`

**Comment by pjworrall** [comment]
This issue was resolved for me when I built GETH from source at v1.4.0. The gas value above was originally 3000000 . When run with the v1.4.0 it didn't encounter a problem and proceeded to log a transaction for the contract. 

It actually moved onto another error but it at least got past the issue reported here.

FYI. If the larger gas value above was used v1.4.0 reports "Error: Exceeds block gas limit" . Do not know what that means yet but I have to move onto the next problem :-). HTH.

**Comment by pjworrall** [comment]
I was wrong. v1.4.0 also will not be happy but it does not report it to the client. It creates a transaction but reports in the log that :+1: 

.. below gas price (tx=1 Shannon ask=18 Shannon). All sequential txs from this address(a57f5476) will be ignored

It appears that I overcame this problem by specifying the gas price in the data object for the new contract. The 18 shannon hint meant that we needed to provide a gas price figure of 18000000010. So the contract.new would be:

```
var cInstance = c.new(
{
    from: addresses[0],
    data: '....[YOUR CONTRACT]...',
    gas: 3000000,
    gasPrice:  	18000000010
}, function(e, contract){
     console.log(e, contract);
    if (typeof contract != 'undefined') {
        console.log('Contract mined! address: ' + contract.address + ' transactionHash: ' +       contract.transactionHash);
console.log(contract.address);
}
});
```
The gasPrice attribute is not shown in the web3 documentation examples. Confusingly, if you use loadScript() in geth to run the code without the gasPrice, as produced by contracts defined in the Solidity Browser, with any unlocked account, it will not complain about gas price too low and work.

This problem is overcome but now I am figuring out why the callback function is not getting the contract.address instance. I get the contract.transactionHash of course but never the contract address.

**Comment by inzhoop** [comment]
@pjworrall The problem still exists!
After receive transactionHash the second callback returns with error:
Contracat transaction couldn't be found after 50 blocks.

Someone could help?
@christianlundkvist
