### ISSUE TITLE
Global leaks

### ISSUE THREAD

**Issue by Schaeff** [ConsenSys/eth-lightwallet#89]
Hi,

As I was testing my application, my testing framework ([lab](https://github.com/hapijs/lab)) detected a bunch of global leaks:

```sh
The following leaks were detected:signTx, legacyDecryptString, multiEncryptString, _bitcore, legacyGenerateEncKey, asymEncryptString, asymDecryptString, recoverAddress, multiDecryptString, signMsg, upgradeOldSerialized, ethUtil, pathKsData, concatSig
```

Is there a reason why globals were necessary here? Can I safely ignore that?

Thanks!

**Comment by christianlundkvist** [comment]
I think this should be fixed by https://github.com/ConsenSys/eth-lightwallet/pull/94.
